- block:
  - name: Check if config dir exists
    stat:
      path: "{{ nginx_conf_ip_path }}"
    register: nginx_conf

  - name: Create nginx data details file
    copy:
      content: "{{ nginx_conf_ip_list_name }}:"
      dest: "{{ nginx_conf_ip_path }}"
      force: false
    when: not nginx_conf.stat.exists

  - include_tasks: subtasks/load_remote_data.yml
    loop: "{{ nginx_conf_host_ip_list }}"
    loop_control:
      loop_var: nginx_data_ip
      label: "{{ nginx_data_ip }}" 
    when:
      nginx_conf_host_ip_list is defined

- block:
  - slurp:
      src: "{{ nginx_conf_ip_path }}"
    register: results
    
  - name: "Parse yml into variable"
    set_fact:
      results:
        "{{ results['content'] | b64decode | from_yaml }}"

- name: nginx_conf_ip_path
  debug:
    msg: "{{ nginx_conf_ip_path }}"

- name: results
  debug:
    msg: "{{ results }}"

#- block:
#  - name: create nginx conf dirs
#    file:
#      path: "{{ item }}"
#      state: directory
#    loop:
#      - "{{ server_conf_path }}"
#      - "{{ upstream_conf_path }}"
#  
#  - include_tasks: subtasks/create_confs.yml
#    loop: "{{ results.nginx_conf_ip_list }}"
